{% set python_min = "3.10" %}
{% set name = "reskit" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/RESKit/archive/v{{ version }}.tar.gz
  sha256: 8c08d5f8c4c2d6747d6c67479c076023a9876c17e0efd6344ea58609936ca2b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - matplotlib-base
    - descartes
    - pandas <2.0.0
    - openpyxl
    - numpy
    - numba
    - scipy <1.15
    - scikit-learn
    - geokit >=1.4.0
    - gdal =3.4
    - netcdf4 >=1.5.3
    - xarray
    - pvlib-python =0.9.0
    - windpowerlib
    - jupyter
    - papermill



test:
  imports:
    - reskit
  commands:
    - conda list
    - python -m pytest
  source_files:
    - .
  requires:
    - python ={{ python_min }}
    - pytest
    - pytest-cov

about:
  home: 'https://github.com/FZJ-IEK3-VSA/reskit'
  license: CC-BY-4.0 AND MIT
  license_file:
    - LICENSE-CC-BY.txt
    - LICENSE-MIT.txt
  summary: Renewable Energy Simulation toolkit

extra:
  recipe-maintainers:
    - chrisjwin
    - julian-belina
    - phil-fzj
