{% set python_min = "3.10" %}
{% set name = "reskit" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/RESKit/archive/v{{ version }}.tar.gz
  sha256: 5a6ef1352c7377fef61a613f2de6c8adb6c9e304b6cb06e81f189add147b3658

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pip
    - matplotlib-base
    - descartes
    - pandas <2.0.0
    - openpyxl
    - numpy 
    - numba
    - scipy <1.15
    - scikit-learn
    - geokit >=1.4.0
    - gdal =3.4
    - netcdf4 >=1.5.3
    - xarray
    - pvlib-python =0.9.0
    - windpowerlib
    - jupyter 
    
    

test:
  imports:
    - reskit
  commands:
    - conda list
    - {{ PYTHON }} -m pytest
  source_files:
    - .
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov

about:
  home: 'https://github.com/FZJ-IEK3-VSA/reskit'
  license: CC-BY-4.0
  license_file:
    - CC-BY-4.0.txt
  summary: Renewable Energy Simulation toolkit

extra:
  recipe-maintainers:
    - julian-belina
