{% set name = "reskit" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/RESKit/archive/v{{ version }}.tar.gz
  sha256: 5a6ef1352c7377fef61a613f2de6c8adb6c9e304b6cb06e81f189add147b3658

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - geokit >=1.2.4
    - numpy <=1.21.4
    - pandas
    - scipy
    - pvlib-python >=0.7.2, <0.9
    - netcdf4 >=1.5.3
    - xarray
    - matplotlib-base
    - descartes
    - gdal >2.0.0, <3.0.0, !=2.4.4
    - scikit-learn
    - papermill
    - jupyter
    - notebook

test:
  imports:
    - reskit
  commands:
    - python -m pytest
  source_files:
    - .
  requires:
    - pytest
    - pytest-cov

about:
  home: 'https://github.com/FZJ-IEK3-VSA/reskit'
  license: MIT
  license_file:
    - LICENSE.txt
  summary: Renewable Energy Simulation toolkit

extra:
  recipe-maintainers:
    - julian-belina
