github:
  branch_name: main
  tooling_branch_name: main
conda_forge_output_validation: true
conda_build:
  pkg_format: '2'

bot:
    inspection: hint-all

noarch_platforms:
  - linux_64
  - win_64
  - osx_64
  - osx_arm64
